    version: '3.9'

    services:
        nginx:
            image: nginx:stable-alpine
            ports:
                - 80:80
            volumes:
                - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                - ./wordpress/:/var/www/html
        mysql:
            image: mysql:latest
            environment: 
                MYSQL_DATABASE: wp
                MYSQL_USER: wp
                MYSQL_PASSWORD: password
                MYSQL_ROOT_PASSWORD: password
        php: 
            build:
                context: .
                dockerfile: php.dockerfile
            volumes:
                - ./wordpress:/var/www/html







